function [SOS, G] = filter500to5k(Fs)
%FILTER500TO5K Returns a discrete-time filter matrix SOS and scale values G.

% MATLAB Code
% Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
% Generated on: 01-Nov-2013 15:23:14

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.

N   = 2;     % Order
Fc1 = 500;   % First Cutoff Frequency
Fc2 =5000;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs);
Hd = design(h, 'butter');

SOS = Hd.sosMatrix;
G = Hd.ScaleValues;

% [EOF]
